services:
  frontend:
    build: .
    container_name: cnweb-frontend
    environment:
      MONGO_URL: mongodb+srv://buivananh01072003:78VGJrX2j7YPdGoV@shopping.7tf8wao.mongodb.net/?retryWrites=true&w=majority
      PORT: 3000
      JWT_SECRET: mysecret
      SECRET_KEY: BfWQTmqfH-6nltqy20yw-JGxGEQ
      NEXT_PUBLIC_API_BASE_URL: "https://cnweb-be.soooverpowered.com/api/"
    expose:
      - 3000
